name: app_links
description: Android App Links, Deep Links, iOs Universal Links and Custom URL schemes handler for Flutter (desktop included).
version: 3.3.0
homepage: https://github.com/llfbandit/app_links

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  app_links_platform_interface: ^1.0.1
  app_links_web: ^1.0.0
  app_links_windows: ^1.0.0
  app_links_macos: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/lints
  lints: ^1.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.llfbandit.app_links
        pluginClass: AppLinksPlugin
      ios:
        pluginClass: AppLinksPlugin
      web:
        default_package: app_links_web
      windows:
        default_package: app_links_windows
      macos:
        default_package: app_links_macos
