name: app_links_macos
description: App Links MacOS implementation for app_links package.
version: 1.0.0
homepage: https://github.com/Village-Baby/app_links/app_links_macos

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  app_links_platform_interface: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: AppLinksMacosPlugin
