name: app_links_platform_interface
description: A common platform interface for the app_links plugin.
homepage: https://github.com/Village-Baby/app_links/app_links_platform_interface
version: 1.0.2

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/plugin_platform_interface
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  # https://pub.dev/packages/lints
  lints: ^1.0.1
